export type BookFormat =
  | 'epub'
  | 'pdf'
  | 'txt'
  | 'mobi'
  | 'cbz'
  | 'cbr'
  | 'cb7'
  | 'cbt'
  | 'cba'
  | 'azw'
  | 'azw3'
  | 'azw4'
  | 'kfx'
  | 'fb2'
  | 'rtf'
  | 'docx'
  | 'odt'
  | 'md'
  | 'markdown'
  | 'html'
  | 'htm'
  | 'djvu'
  | 'xps'
  | 'lit'
  | 'pdb'
  | 'unknown'

export function detectFormat(file: File): BookFormat {
  const name = file.name.toLowerCase()
  if (name.endsWith('.epub')) return 'epub'
  if (name.endsWith('.pdf')) return 'pdf'
  if (name.endsWith('.txt')) return 'txt'
  if (name.endsWith('.mobi')) return 'mobi'
  if (name.endsWith('.cbz')) return 'cbz'
  if (name.endsWith('.cbr')) return 'cbr'
  if (name.endsWith('.cb7')) return 'cb7'
  if (name.endsWith('.cbt')) return 'cbt'
  if (name.endsWith('.cba')) return 'cba'
  if (name.endsWith('.azw')) return 'azw'
  if (name.endsWith('.azw3')) return 'azw3'
  if (name.endsWith('.azw4')) return 'azw4'
  if (name.endsWith('.kfx')) return 'kfx'
  if (name.endsWith('.fb2')) return 'fb2'
  if (name.endsWith('.rtf')) return 'rtf'
  if (name.endsWith('.docx')) return 'docx'
  if (name.endsWith('.odt')) return 'odt'
  if (name.endsWith('.md')) return 'md'
  if (name.endsWith('.markdown')) return 'markdown'
  if (name.endsWith('.html')) return 'html'
  if (name.endsWith('.htm')) return 'htm'
  if (name.endsWith('.djvu')) return 'djvu'
  if (name.endsWith('.xps')) return 'xps'
  if (name.endsWith('.lit')) return 'lit'
  if (name.endsWith('.pdb')) return 'pdb'
  return 'unknown'
}
