import { detectFormat } from './format'

test('detects format by file extension', () => {
  const epub = new File(['x'], 'book.epub')
  const pdf = new File(['x'], 'book.pdf')
  const txt = new File(['x'], 'book.txt')
  const mobi = new File(['x'], 'book.mobi')
  const cbz = new File(['x'], 'book.cbz')
  const cbr = new File(['x'], 'book.cbr')
  const cb7 = new File(['x'], 'book.cb7')
  const cbt = new File(['x'], 'book.cbt')
  const cba = new File(['x'], 'book.cba')
  const azw = new File(['x'], 'book.azw')
  const azw3 = new File(['x'], 'book.azw3')
  const azw4 = new File(['x'], 'book.azw4')
  const kfx = new File(['x'], 'book.kfx')
  const fb2 = new File(['x'], 'book.fb2')
  const rtf = new File(['x'], 'book.rtf')
  const docx = new File(['x'], 'book.docx')
  const odt = new File(['x'], 'book.odt')
  const md = new File(['x'], 'book.md')
  const markdown = new File(['x'], 'book.markdown')
  const html = new File(['x'], 'book.html')
  const htm = new File(['x'], 'book.htm')
  const djvu = new File(['x'], 'book.djvu')
  const xps = new File(['x'], 'book.xps')
  const lit = new File(['x'], 'book.lit')
  const pdb = new File(['x'], 'book.pdb')
  const other = new File(['x'], 'book.bin')

  expect(detectFormat(epub)).toBe('epub')
  expect(detectFormat(pdf)).toBe('pdf')
  expect(detectFormat(txt)).toBe('txt')
  expect(detectFormat(mobi)).toBe('mobi')
  expect(detectFormat(cbz)).toBe('cbz')
  expect(detectFormat(cbr)).toBe('cbr')
  expect(detectFormat(cb7)).toBe('cb7')
  expect(detectFormat(cbt)).toBe('cbt')
  expect(detectFormat(cba)).toBe('cba')
  expect(detectFormat(azw)).toBe('azw')
  expect(detectFormat(azw3)).toBe('azw3')
  expect(detectFormat(azw4)).toBe('azw4')
  expect(detectFormat(kfx)).toBe('kfx')
  expect(detectFormat(fb2)).toBe('fb2')
  expect(detectFormat(rtf)).toBe('rtf')
  expect(detectFormat(docx)).toBe('docx')
  expect(detectFormat(odt)).toBe('odt')
  expect(detectFormat(md)).toBe('md')
  expect(detectFormat(markdown)).toBe('markdown')
  expect(detectFormat(html)).toBe('html')
  expect(detectFormat(htm)).toBe('htm')
  expect(detectFormat(djvu)).toBe('djvu')
  expect(detectFormat(xps)).toBe('xps')
  expect(detectFormat(lit)).toBe('lit')
  expect(detectFormat(pdb)).toBe('pdb')
  expect(detectFormat(other)).toBe('unknown')
})
