import { detectFormat } from './format'

test('detects format by file extension', () => {
  const epub = new File(['x'], 'book.epub')
  const pdf = new File(['x'], 'book.pdf')
  const txt = new File(['x'], 'book.txt')
  const mobi = new File(['x'], 'book.mobi')
  const cbz = new File(['x'], 'book.cbz')
  const cbr = new File(['x'], 'book.cbr')
  const cb7 = new File(['x'], 'book.cb7')
  const azw = new File(['x'], 'book.azw')
  const azw3 = new File(['x'], 'book.azw3')
  const fb2 = new File(['x'], 'book.fb2')
  const rtf = new File(['x'], 'book.rtf')
  const docx = new File(['x'], 'book.docx')
  const other = new File(['x'], 'book.bin')

  expect(detectFormat(epub)).toBe('epub')
  expect(detectFormat(pdf)).toBe('pdf')
  expect(detectFormat(txt)).toBe('txt')
  expect(detectFormat(mobi)).toBe('mobi')
  expect(detectFormat(cbz)).toBe('cbz')
  expect(detectFormat(cbr)).toBe('cbr')
  expect(detectFormat(cb7)).toBe('cb7')
  expect(detectFormat(azw)).toBe('azw')
  expect(detectFormat(azw3)).toBe('azw3')
  expect(detectFormat(fb2)).toBe('fb2')
  expect(detectFormat(rtf)).toBe('rtf')
  expect(detectFormat(docx)).toBe('docx')
  expect(detectFormat(other)).toBe('unknown')
})
